spring:
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: thread
        format_sql: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: removed@gmail.com
    password: Password1@
    properties:
      mail:
        smtp:
          starttls:
            enable: true

